### ISSUE TITLE
Upload to material design icon website?

### ISSUE THREAD

**Issue by lolouk44** [hulkhaugen/hass-bha-icons#1]
No an issue, rather a request: are you planning on uploading these to material design icon's website so that everybody else can automatically benefit?

**Comment by james-fry** [comment]
Contributing to MDI is very painful.
Unless you are one of the small number of people who are selected to be able to add icons it takes months or years to add. I know - [I did it.](https://github.com/Templarian/MaterialDesign/issues/1964)
This repo is a good way to get icons that (perhaps a small number of) people need to use rapidly, or that are not accepted by MDI.

@hulkhaugen are you open to PRs for other peoples icons?
Or should I start a different repo as a public contrib repo?

**Comment by hulkhaugen** [comment]
> No an issue, rather a request: are you planning on uploading these to material design icon's website so that everybody else can automatically benefit?

I have submitted most of them long time ago, but because of their progress, I decided to make my own. Only the Pi-Hole has been added so far. https://github.com/Templarian/MaterialDesign/issues/3836

> Contributing to MDI is very painful.
> Unless you are one of the small number of people who are selected to be able to add icons it takes months or years to add. I know - [I did it.](https://github.com/Templarian/MaterialDesign/issues/1964)
> This repo is a good way to get icons that (perhaps a small number of) people need to use rapidly, or that are not accepted by MDI.
> 
> @hulkhaugen are you open to PRs for other peoples icons?
> Or should I start a different repo as a public contrib repo?

Sure, bring it on :D

**Comment by lolouk44** [comment]
Thanks both :)

**Comment by mririgoyen** [comment]
Hey there, I'm a Core Contributor to the MDI project. I actually have some really good news... The maintainer of the project has recently greatly improved the tooling, giving all the Core Contributors the ability to add icons! Before, everything went through him, so it slowed the process greatly.

We're in the beginning stages of working the kinks out, but I can tell you that we have 2 new versions staged and ready to go at this very moment. Our hope is to greatly increase the amount of times we release with new icons! 😄 

That being said, I have personally chimed in and finalized 5 icons in Templarian/MaterialDesign#3836 to be included in our 4.1 release. There are a couple other icons I see here, (like that chandelier!) that might be worth opening issues for to have included. Just please, one icon per issue (multi-icon issues become unruly) and make sure you're following [Material guidelines](https://material.io/design/iconography/system-icons.html#design-principles) (makes it much quicker to get accepted).

Thanks!

**Comment by hulkhaugen** [comment]
Oh cool, yea I will look into that. ATM i'm very busy, but later I will.
