### ISSUE TITLE
Icon will not show in header

### ISSUE THREAD

**Issue by mdezzi** [hulkhaugen/hass-bha-icons#10]
I was having an issue with the Roborock icon not showing on a page header, but still showing in the regular lovelace cards. I was able to solve this issue by adding the following to my configuration.yaml: 

```
frontend:
  extra_module_url:
    - /hacsfiles/hass-bha-icons/hass-bha-icons.js
```

I'm not sure if this can be fixed without adding that line to the config, or if the documentation should be updated.

**Comment by hulkhaugen** [comment]
Documentation has it under manual install, but it could be more informative about the differences. Thanks for pointing that out.
