### ISSUE TITLE
Adding more icons

### ISSUE THREAD

**Issue by antonjarl** [hulkhaugen/hass-bha-icons#11]
Hi,

I've expanded your icon set with some more lamp icons in a similar style that you've already made. Would you like me to create a PR to add those or are you happy with the ones you got?
<img width="1680" alt="2020-10-09 - epy5s" src="https://user-images.githubusercontent.com/10976586/95585085-03eccc80-0a3f-11eb-8fda-41ef11f9a901.png">

If you'd like I can pack those new icons together and create a PR.

**Comment by hulkhaugen** [comment]
Sure, why not? However, I would like to comment on the first one, "Ljusslinga, sovrummet", I think the bulb shape should be the same as the regular lightbulb shape for consistency, and just change the bulb thread to a square base as in your example.

**Comment by M0E-lnx** [comment]
+1 on this PR
Looking for an icon similar to what you have on the top right corner of the screenshot there

**Comment by ur7x** [comment]
Sorry for the noob question but where can I find a copy of svg of the Upper right one?  It is almost exactly what I need for my house full of "light cans"

**Comment by antonjarl** [comment]
@ur7x Do you mean the spotlight one, circled with red?

You can have it here:
https://drive.google.com/file/d/15qELWwDkJVklOSVUyuYYObp4bA-wPO7V/view?usp=sharing

**Comment by ur7x** [comment]
Perfect!  Thanks so much
