### ISSUE TITLE
Compatible with the latest Home Assistant 2021 ??

### ISSUE THREAD

**Issue by healeydave** [hulkhaugen/hass-bha-icons#12]
Apologies if this is a dumb question but I tried adding to a new home assistant installation (a few days ago) and I get a "Invalid Add-on repository!". 

Supervisor > Add-on-store > Repositories > https://github.com/hulkhaugen/hass-bha-icons

.....is the right place to add isn't it?

**Comment by hulkhaugen** [comment]
That is the correct repository, but this is not an add-on. Add-ons are typically entirely separate "programs" like Plex, Node-Red, AdGuard, Mosquitto etc, and they run in isolated Docker containers, parallel with Home Assistant. This is a custom integration (plugin) which can be manually installed by copying the `hass-bha-icons.js` file to the `/config/www/` folder and add it in the `configuration.yaml` file. However, the most popular and easiest way to do this is using the [HACS](https://hacs.xyz/) integration, which is a "Custom Integration Store" that has a nice UI and a large library of integrations.

**Comment by healeydave** [comment]
Ah, sorry, my mistake, I'm new to HASS. I followed the instructions for HACS but assumed this was the resources section in HASS and not a separate tool. Thanks.
