### ISSUE TITLE
Icons work in mobile app?

### ISSUE THREAD

**Issue by healeydave** [hulkhaugen/hass-bha-icons#13]
Hi, 
I got your package installed in the end, thanks for your help.
Probably another daft questions but I noticed the icons don't appear in the mobile app, is that normal?

Thanks.
Dave.

**Comment by hulkhaugen** [comment]
No, that is not normal and probably related to cache that needs to be cleared. Have you tried opening you dashboard in incognito/private mode?

**Comment by healeydave** [comment]
Huh, I just went to check and its working now, weird, oh well, thanks again 👍
