### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by HydrelioxGitHub** [hulkhaugen/hass-bha-icons#14]
I've read the FAQ about icons being replaced by white space. I've tried incognito mode but nothing change. I use HACS. 
Do I have to provide something to help resolving this ?

**Comment by hulkhaugen** [comment]
I see that the documentation is a bit inconsistent, I need to correct that. Did you add the module in `Configuration > Lovelace Dashboards > Resources`? If not, you need to add it there, using the `/hacsfiles/hass-bha-icons/hass-bha-icons.js`. I should make HACS add that resource automatically on installation...

Thanks for pointing that out, and let me know if it works out.

**Comment by HydrelioxGitHub** [comment]
I've checked the place you mentioned, and the ressource is already there. I didn't do anything for this.

But it seems the missing icon issue isn't consistent. Sometimes it appears sometimes not. And this this is the same across browser and on the HA Companion Android app.

Thanks for your time and your talent btw.

**Comment by hulkhaugen** [comment]
Are you perhaps hosting HA through Cloudflare or similar? I know that Cloudflare caches data, and you can set TTL (Time to live) for cache, as well as manually clear parts of or all cache.

**Comment by HydrelioxGitHub** [comment]
HA is hosted at my home on a rpi3. The problem occurs from inside my local network and when I access it from the Internet. I use duckdns to handle my domain name.

**Comment by hulkhaugen** [comment]
Ok, I'm not sure if or how DuckDNS handles cache. Does it happen when you access it through your ip instead of duckdns?

Another thing you can try, assuming you're using Chrome or Edge, is to right click the website and click `Inspect`. Click on the `Network` tab, and check `Disable cache`. Then refresh the site with that panel open.

**Comment by HydrelioxGitHub** [comment]
It's get weirder. I've disable cache. I can see in the network that the js file is correctly loaded.

![image](https://user-images.githubusercontent.com/15862735/111537812-2f04e600-876c-11eb-9fa4-899b7a761089.png)

When I'm in the front panel the icons are still missing but if I click on one to get details, the icon display correctly.

![image](https://user-images.githubusercontent.com/15862735/111538018-74c1ae80-876c-11eb-8585-d8b687ecc110.png)

I'm not enough skilled to understand why ....

**Comment by clemalex824** [comment]
To be sure it's not the cache, add a version number after the file extension.
![image](https://user-images.githubusercontent.com/35152089/111919018-17896e00-8a88-11eb-8bbb-bd1975f69f8a.png)
And clear cache (CTRL+F5 or CTRL+SHIFT+R)

**Comment by HydrelioxGitHub** [comment]
I've tried but nothing more, except that my path to hass-bha-icons.js is not the same than mine : /hacsfiles/hass-bha-icons/hass-bha-icons.js?v=1

**Comment by hulkhaugen** [comment]
This doesn't make any sense. Have you only set it up for Lovelace as described above, or have you also added the following to your configuration.yaml file?

```
frontend:
  extra_module_url:
    - /hacsfiles/hass-bha-icons/hass-bha-icons.js
```
Even though your actual path is `.../config/www/community/hass-bha-icons`, the correct input should be `/hacsfiles/hass-bha-icons/hass-bha-icons.js`, as HACS creates a symlink to that folder.

And just to be sure that we are not looking in the wrong place, have you double checked that your Lovelace is configured correctly?
```
entities:
  - entity: light.livingroom_floorlamp
    icon: bha:floor-lamp
```
If you misspell the icon string, Lovelace will try to load an icon that isn't there, and the result will be a blank/missing icon.
