### ISSUE TITLE
icons don't show anymore

### ISSUE THREAD

**Issue by kongo09** [hulkhaugen/hass-bha-icons#15]
I've just updated to your latest version and now the icons don't show anymore in Lovelace. Nothing else changed.

**Comment by kongo09** [comment]
I think I found the bug you introduced: #16

**Comment by alicialiali** [comment]
Here too, after the new update the icons are gone!

**Comment by eddiegrau** [comment]
I also noticed my icons missing after updating to the latest version.

**Comment by hulkhaugen** [comment]
Oops, my bad. Should be fixed now.
