### ISSUE TITLE
Adding icons ? 

### ISSUE THREAD

**Issue by clemalex824** [hulkhaugen/hass-bha-icons#17]
Thank you so much for sharing your work.

I realized some icons and I want to offer them to you:

Tell me if you want one (or more) and I'll do a PR

![20210408_002414](https://user-images.githubusercontent.com/35152089/113942737-9826c900-9801-11eb-9236-b402cb518bb9.jpg)
![20210408_002438](https://user-images.githubusercontent.com/35152089/113942743-9e1caa00-9801-11eb-8f03-4706ad50e294.jpg)
![20210408_002501](https://user-images.githubusercontent.com/35152089/113942767-a7a61200-9801-11eb-8a29-142f839c0841.jpg)

I use them like this:
![20210408_003320](https://user-images.githubusercontent.com/35152089/113943017-1edba600-9802-11eb-8180-080ab6ee1446.jpg)
![iMarkup_20210408_003252](https://user-images.githubusercontent.com/35152089/113943058-31ee7600-9802-11eb-9f03-b8913e8e0e90.jpg)

Thanks again for sharing And show how to use your own icons

_Sorry about my English_

**Comment by jybi89** [comment]
it's a very good job! congratulations !

**Comment by hulkhaugen** [comment]
Several of these should be easy to add. Some of them has a lot of detail which i think would not look to good in a tiny icon. Looking at the moon cake, filament, radiator and floor heater. The filament should be easy enough to find an alternative design for. MDI already have a simplified HA logo with less detail. What even is Moon Cake?

Anyway, I'm busy the next week, but can look at this maybe next week.

**Comment by clemalex824** [comment]
I agree with you. I don't plan on using the icons in a 24x24 format so I'm not looking at the level of detail. It is true that it can be frustrating for a user. Just tell me (when you have the time) which ones I need to do a PR and for the others they will be available on my github. MoooCake is a nod to a friend and is not to be considered

**Comment by clemalex824** [comment]
Add 24x24 render : 

![image](https://user-images.githubusercontent.com/35152089/114020449-e672b100-986f-11eb-88b8-b9bf1a93fb39.png)

**Comment by m1ke-hub** [comment]
@clemalex824 yeah! You got some great looking icons there! Mind sharing both floor heater icons and the phoscon? I don't know where I could find them on your github.

Also, here are my custom icons, if anyone is interested:

![icons](https://user-images.githubusercontent.com/57773976/114181213-81878b80-9941-11eb-9662-8796f278c126.png)

**Comment by clemalex824** [comment]
> I don't know where I could find them on your github

Because I'd rather try to put the icons together here  😉

Why not do a PR or a Issue like me For them to add to this repository?

when @hulkhaugen will have decided which icons it wishes to get, I will build my repository with the icons not retained here. 

Let's just be patient. 😇

**Comment by hulkhaugen** [comment]
@clemalex824 I think the following icons will be nice additions:
- phoscom
- openwrt
- NAS
- Node-RED (See this link https://nodered.org/about/resources/)
- NGINX Proxy Manager outline
- DSM

For filament, I think we should try to come up with something with less detail that looks better in small sizes. Personally, i don't like text in icons, but such as DSM, i guess there is no good alternative.

@migo-dev 
I think the following will be good additions:
- deCONZ
- Dyson Fan
- Hue wellness
- Both floolamps
- Ceiling lamp
- Ceiling lamp 3 off

I have not double checked, but I assume that the ones you suggested are not already in the MDI pack?

**Comment by clemalex824** [comment]
@hulkhaugen

Ok I do it today i think

I took into account the change requested for Nodered without the text.

**Comment by clemalex824** [comment]
> For filament, I think we should try to come up with something with less detail that looks better in small sizes.

Based on https://www.wish.com/product/5e967ec794e8490ea8b7e186?hide_login_modal=true&share=web

![image](https://user-images.githubusercontent.com/35152089/114306633-a82df980-9adc-11eb-9a3a-fe97b34c3e63.png)
![image](https://user-images.githubusercontent.com/35152089/114306582-787ef180-9adc-11eb-8ea3-a16ad8bfaa41.png)

is good to a PR ?

**Comment by hulkhaugen** [comment]
I like the new filament icon better, but I still think it should be refined some more as per the [Material guidelines](https://material.io/design/iconography/system-icons.html#grid-and-keyline-shapes). I had a look at a few of your icon contributions, and I've updated Nginx and OpenWRT, haven't had time to look at the rest of them. I'm not a nazi, but I think we should apply the Material guidelines as well as possible.

I can review and update the rest if you want to, or you can finetune themselves if you prefer. Anyways, thanks for your contributions :)

**Comment by clemalex824** [comment]
I'll let you do it. , I have absolutely no time to do it.

Thanks.

**Comment by clemalex824** [comment]
Just one question @hulkhaugen : 

Why **b**ha ? what is meaning b letter?

**Comment by hulkhaugen** [comment]
I kinda rushed the decision on the abbreviation when I made this pack. but BH are my initials, and HA is Home Assistant.

**Comment by ur7x** [comment]
Any chance that someone could draft a "pot light"  also known as a "recessed light" or a "light can"  my house is full of them and I can't find a decent icon for them any where. 

Oh and this plug in is the best thing ever!

**Comment by clemalex824** [comment]
> Any chance that someone could draft a "pot light" also known as a "recessed light" or a "light can" my house is full of them and I can't find a decent icon for them any where.
> 
> Oh and this plug in is the best thing ever!

https://github.com/hulkhaugen/hass-bha-icons/issues/11#issue-718123142

![image](https://user-images.githubusercontent.com/35152089/114787807-a5ebc980-9d80-11eb-809f-5577d8ed2e2b.png)

**Comment by broyuken** [comment]
Could I request the following icon be added for B-Hyve Irrigation systems? Should I create a PR or could somebody add it to this request?

![image](https://user-images.githubusercontent.com/1593391/115074604-ea35b180-9ec7-11eb-9f59-3ff89b5635c9.png) or 
![image](https://user-images.githubusercontent.com/1593391/115074719-181af600-9ec8-11eb-8817-fbafdbdeec5e.png)

**Comment by ur7x** [comment]
I have successfully implemented  "Moon Cake"  And I'm using him as my "automation" icon...
Where is he from?  What is the inside joke? 


 'moon-cake':
     'm5.1 0.18c-0.13-0.0079-0.27 0.024-0.38 0.098-0.17 0.12-0.3 0.55-0.24 0.79 0.051 0.2 0.35 0.43 0.57 0.43 0.22 0.0014 0.3 0.071 0.36 0.3 0.027 0.11 0.16 0.41 0.29 0.66s0.27 0.54 0.29 0.63c0.028 0.091 0.15 0.39 0.28 0.66 0.46 0.99 0.56 1.3 0.47 1.5-0.036 0.066-0.11 0.12-0.16 0.12-0.053 0-0.096 0.027-0.096 0.059 0 0.032-0.23 0.17-0.51 0.31s-0.53 0.27-0.54 0.29c-0.018 0.021-0.15 0.095-0.28 0.16-0.14 0.069-0.25 0.15-0.25 0.18 0 0.031-0.041 0.057-0.09 0.057s-0.15 0.051-0.23 0.12c-0.076 0.064-0.22 0.18-0.31 0.25-0.38 0.29-0.92 0.79-1.2 1.1-0.15 0.17-0.4 0.46-0.55 0.64-0.15 0.18-0.28 0.36-0.28 0.4 0 0.041-0.048 0.12-0.11 0.17-0.06 0.05-0.15 0.18-0.2 0.29-0.05 0.11-0.15 0.29-0.22 0.4-0.41 0.65-0.85 2.2-0.91 3.1-0.042 0.74 0.068 1.8 0.22 2.1 0.051 0.11 0.092 0.26 0.092 0.34 0 0.21 0.22 0.81 0.46 1.3 0.36 0.66 0.56 1 0.66 1.1 0.054 0.063 0.16 0.2 0.23 0.31s0.18 0.24 0.24 0.3c0.06 0.055 0.32 0.33 0.58 0.6l0.47 0.5-0.14 0.59c-0.11 0.45-0.13 0.71-0.1 1.1 0.036 0.47 0.27 1.4 0.37 1.5 0.027 0.018 0.085 0.1 0.13 0.18 0.043 0.082 0.23 0.27 0.42 0.41 0.19 0.15 0.38 0.3 0.43 0.33 0.16 0.14 0.85 0.28 1.4 0.29 0.83 0.011 1.4-0.22 2-0.75 0.51-0.5 0.56-0.57 0.61-0.79l0.043-0.22 0.44 0.045c0.66 0.067 0.86 0.1 1.1 0.17 0.31 0.085 2.9 0.087 3.2 2e-3 0.13-0.036 0.48-0.1 0.79-0.14 0.31-0.04 0.71-0.11 0.88-0.16 0.18-0.051 0.34-0.08 0.37-0.062 0.026 0.016 0.051 0.12 0.055 0.22 0.0063 0.22 0.12 0.47 0.21 0.47 0.035 0 0.064 0.047 0.064 0.1 0 0.15 0.72 0.84 1.1 1 0.16 0.083 0.48 0.18 0.69 0.21 0.22 0.03 0.43 0.058 0.47 0.062 0.18 0.02 0.85-0.15 1.2-0.29 0.34-0.15 0.98-0.68 0.98-0.81 0-0.034 0.055-0.13 0.12-0.22 0.069-0.087 0.19-0.36 0.26-0.61 0.25-0.83 0.15-2-0.23-2.5-0.099-0.15-0.09-0.17 0.31-0.57 0.43-0.43 0.79-0.86 0.84-0.98 0.014-0.038 0.069-0.12 0.12-0.18 0.19-0.21 0.62-0.95 0.72-1.2 0.053-0.15 0.12-0.3 0.15-0.34 0.075-0.097 0.3-0.81 0.47-1.5 0.19-0.76 0.19-2.2 2e-3 -2.8-0.073-0.21-0.13-0.47-0.13-0.58 0-0.33-0.61-1.7-1.1-2.3-0.44-0.65-1.4-1.7-1.9-2.1-0.13-0.096-0.29-0.23-0.36-0.29-0.25-0.21-0.59-0.44-0.83-0.56-0.13-0.064-0.25-0.13-0.26-0.16-0.018-0.022-0.13-0.08-0.25-0.13-0.37-0.15-0.42-0.37-0.2-0.86 0.077-0.17 0.21-0.45 0.29-0.63 0.084-0.18 0.2-0.48 0.26-0.66 0.059-0.18 0.19-0.51 0.29-0.73s0.27-0.62 0.38-0.89l0.19-0.49 0.41-0.16c0.44-0.17 0.46-0.2 0.42-0.71-0.025-0.31-0.25-0.48-0.49-0.5l0.029-0.023c-0.25-0.015-0.52 0.12-0.63 0.43-0.033 0.087-0.042 0.36-0.023 0.61 0.027 0.36 0.0096 0.5-0.086 0.66-0.066 0.12-0.44 0.85-0.84 1.6-0.85 1.7-0.91 1.8-1.2 1.7-0.097-0.023-0.21-0.065-0.24-0.092-0.036-0.027-0.18-0.084-0.33-0.13-0.15-0.044-0.32-0.1-0.4-0.13-0.24-0.1-1.5-0.39-2.2-0.49-1.4-0.21-3.8-0.11-4.9 0.2-0.48 0.13-1.1 0.29-1.4 0.33-0.1 0.021-0.24-0.0087-0.34-0.072-0.16-0.1-0.25-0.25-0.73-1.2-0.11-0.22-0.22-0.41-0.25-0.43-0.024-0.018-0.13-0.21-0.22-0.43-0.099-0.22-0.2-0.41-0.22-0.43-0.022-0.018-0.16-0.25-0.3-0.52-0.21-0.4-0.24-0.51-0.18-0.61 0.13-0.21 0.093-0.74-0.061-0.9-0.08-0.085-0.2-0.13-0.33-0.14zm6.3 4.9c0.27-0.0095 0.55-0.0083 0.83 2e-3 0.32 0.012 0.64 0.035 0.97 0.072 1.4 0.16 1.8 0.37 1.8 1 0.012 0.32-0.16 0.6-0.43 0.69-0.2 0.071-1.5-0.069-1.7-0.18-0.084-0.045-0.7-0.066-1.7-0.062-1.3 4e-3 -1.7 0.026-2.3 0.14-0.42 0.077-0.84 0.14-0.94 0.14-0.22 0-0.97 0.23-1.3 0.4-0.13 0.064-0.48 0.24-0.78 0.39-0.76 0.38-1.3 0.37-1.2-0.029 0.044-0.16 0.61-0.63 1-0.85 2-1.1 3.9-1.7 5.8-1.7l-0.049-0.012zm5.4 0.96-0.014 0.0098c0.4-2e-7 0.46 0.019 0.67 0.21 0.2 0.19 0.23 0.25 0.23 0.55 0 0.33-0.027 0.39-0.34 0.74-0.12 0.13-0.21 0.16-0.51 0.16-0.31 0-0.4-0.03-0.59-0.2-0.43-0.38-0.44-0.81-0.035-1.3 0.13-0.15 0.2-0.17 0.59-0.17zm-11 3.6c0.63 0.056 1.3 0.3 1.8 0.63 0.27 0.19 0.88 0.89 0.88 1 0 0.049 0.025 0.09 0.057 0.09 0.11 0 0.35 0.93 0.36 1.4 0.0039 0.45-0.15 1.1-0.32 1.3-0.049 0.057-0.09 0.13-0.09 0.17-4.7e-4 0.11-0.62 0.77-0.93 0.98-0.4 0.28-0.72 0.42-1.3 0.57-0.57 0.15-0.71 0.15-1.4 0.027-0.95-0.17-1.6-0.59-2.2-1.4-0.84-1.1-0.7-2.7 0.35-3.7 0.55-0.54 1.2-0.83 2.2-0.98 0.18-0.025 0.38-0.027 0.58-0.0078l0.014-0.08zm12 0.09-0.0098 0.051c1.1 0 1.7 0.27 2.5 1 0.44 0.44 0.74 1.1 0.84 1.8 0.046 0.32-0.11 1.1-0.26 1.4-0.055 0.085-0.1 0.19-0.1 0.24 0 0.048-0.082 0.18-0.18 0.29-0.1 0.11-0.23 0.27-0.29 0.35-0.061 0.081-0.18 0.19-0.27 0.25-0.088 0.059-0.28 0.18-0.42 0.28-0.14 0.093-0.46 0.25-0.7 0.35-0.39 0.15-0.54 0.18-1.2 0.17-1.2-0.0062-2-0.34-2.8-1.3-0.099-0.11-0.3-0.5-0.46-0.88-0.072-0.17-0.11-0.45-0.11-0.88 0-0.68 0.16-1.2 0.49-1.7 0.091-0.12 0.17-0.24 0.17-0.27 0.0061-0.089 0.67-0.59 1-0.77 0.57-0.29 0.99-0.38 1.8-0.38zm-13 1.8c-0.16-0.0033-0.34 0.054-0.57 0.17-0.31 0.16-0.42 0.31-0.55 0.69-0.09 0.28 7.5e-4 0.77 0.19 0.98 0.091 0.11 0.49 0.32 0.74 0.4 0.054 0.017 0.14 0.022 0.2 0.0098 0.23-0.051 0.43-0.12 0.46-0.16 0.018-0.022 0.091-0.073 0.16-0.11 0.24-0.13 0.39-0.41 0.41-0.77 0.034-0.46-0.12-0.75-0.54-1-0.19-0.13-0.34-0.19-0.51-0.19l0.012-0.02zm13 0.25c-0.26 0-0.46 0.028-0.46 0.062s-0.062 0.08-0.14 0.11c-0.2 0.062-0.52 0.61-0.52 0.87 0 0.12 0.043 0.33 0.098 0.46 0.11 0.27 0.51 0.66 0.72 0.71 0.22 0.048 0.7-0.012 0.82-0.1 0.71-0.54 0.8-1.2 0.24-1.8-0.29-0.3-0.29-0.3-0.76-0.3l2e-3 -0.012zm-7.6 2.1c0.023-0.0099 0.061-0.0049 0.12 0.014 0.082 0.026 0.58 0.059 1.1 0.072 0.53 0.013 0.96 0.048 0.97 0.076 0.028 0.089-0.073 0.19-0.37 0.38-0.28 0.18-0.81 0.27-1.1 0.19-0.3-0.088-0.77-0.48-0.77-0.65 0-0.043 0.0086-0.068 0.031-0.078l0.018-0.0039zm9.3 4.2 0.051 0.0039c0.068 0.0056 0.1 0.045 0.1 0.12 0 0.18-1.6 1.5-1.8 1.5-0.075 0-0.5 0.24-0.72 0.41-0.087 0.066-0.2 0.12-0.26 0.12-0.059 5.6e-4 -0.42 0.12-0.8 0.26s-0.77 0.26-0.87 0.26-0.29 0.044-0.43 0.098-0.67 0.16-1.2 0.23c-0.9 0.13-2.5 0.21-3.1 0.16-0.31-0.028-1.2-0.17-2-0.3-0.23-0.04-0.43-0.098-0.45-0.13-0.02-0.032-0.12-0.06-0.21-0.061-0.098-7.2e-4 -0.42-0.089-0.71-0.19-0.29-0.11-0.63-0.23-0.76-0.27-0.26-0.089-0.4-0.16-0.92-0.43-0.38-0.2-0.44-0.23-0.75-0.42-0.28-0.17-1-0.7-1-0.76-0.012-0.028-0.059-0.049-0.11-0.049-0.1 0-0.3-0.22-0.3-0.33 0-0.13 0.41-0.033 1.1 0.26 1.3 0.56 1.5 0.66 1.9 0.73 0.18 0.041 0.5 0.13 0.72 0.2 0.39 0.12 0.75 0.19 1.6 0.33 0.54 0.085 3.4 0.091 4 0.0078 0.22-0.034 0.67-0.1 1-0.14 0.33-0.044 0.76-0.12 0.96-0.17s0.54-0.11 0.76-0.13c0.41-0.039 1.2-0.23 1.5-0.39 0.12-0.051 0.34-0.11 0.49-0.14 0.27-0.041 1.3-0.42 1.9-0.69 0.14-0.066 0.24-0.095 0.31-0.09zm-15 3.3 0.053 0.059c0.09-0.011 0.2 0.055 0.2 0.15 0 0.17 0.26 0.41 0.55 0.52 0.15 0.055 0.54 0.11 0.87 0.13 0.77 0.043 1.1 0.17 1.2 0.5 0.14 0.28 0.11 0.39-0.18 0.65-0.19 0.18-0.75 0.24-1.2 0.14-0.55-0.12-1.2-0.67-1.5-1.3-0.15-0.31-0.18-0.7-0.072-0.81 0.023-0.023 0.05-0.035 0.08-0.039zm15 0.52c0.19 0.0016 0.37 0.035 0.44 0.1 0.056 0.056 0.14 0.22 0.18 0.35 0.061 0.2 0.058 0.29-0.023 0.44-0.12 0.24-0.34 0.49-0.42 0.49-0.033 0-0.18 0.059-0.32 0.13-0.27 0.14-0.84 0.17-1.2 0.066-0.72-0.24-1.6-1-1.2-1.1 0.045-0.017 0.14-0.0068 0.21 0.021 0.073 0.029 0.32 0.054 0.55 0.057 0.41 0.0045 0.62-0.068 1.3-0.43 0.11-0.064 0.32-0.093 0.51-0.092l-0.025-0.033z',

**Comment by hulkhaugen** [comment]
added `b-hyve`, `ceiling-downlight` and `ceiling-spot-lamp`

**Comment by clemalex824** [comment]
@ur7x 👍

It was a nod to a friend when I showed him that we could do whatever we wanted with HA

Mine mooncake :
```
  'mooncake':
    'M 19.550781,0.55859375 C 19.383221,0.5403333 19.190283,0.59223608 18.980469,0.75 18.466887,1.254422 19.156958,1.9098445 18.589844,2.4355469 18.075106,3.4443025 17.566331,4.4555068 17.052734,5.4648438 14.124417,4.2525398 10.768758,4.1610851 7.765625,5.1582031 7.3211597,5.0864515 7.2288202,4.4045781 6.9550781,4.0488281 6.5586292,3.2950499 6.1291014,2.5579748 5.7578125,1.7929688 6.0667122,1.3455284 5.9735716,0.60296352 5.3203125,0.5703125 4.3410034,0.5513345 4.318315,2.2114563 5.3730469,1.9824219 5.9011323,3.1120882 6.4219553,4.2532664 6.9042969,5.4023438 6.45974,5.7752217 5.7991125,5.9503561 5.3085938,6.3144531 2.7567839,7.8470773 0.82834484,10.740707 1.1464844,13.798828 c 0.157332,2.091214 1.2765241,3.908253 2.8222656,5.267578 l -0.025391,-0.0039 c -0.4931851,1.269634 -0.3279592,3.026953 0.9277344,3.814453 1.2290802,0.785131 3.0321394,0.542703 3.8671874,-0.707031 0.3511054,-0.285878 0.3708557,-0.472455 0.2480469,-0.607422 2.1210469,0.4894 4.3693829,0.453436 6.4687499,-0.113281 -0.116653,0.270374 0.121162,0.685935 0.472656,1.02539 1.071413,1.524161 3.721342,1.185457 4.392578,-0.544921 0.358603,-0.932387 0.358618,-2.172544 -0.121093,-3.00586 1.971271,-1.786401 3.143049,-4.566527 2.523437,-7.197266 -0.518353,-2.6221609 -2.54499,-4.7112148 -4.86914,-5.8925776 -0.124515,-0.3830679 0.2718,-0.8371229 0.380859,-1.25 0.362488,-0.8676314 0.722506,-1.7370972 1.087891,-2.6035156 1.18053,0.065388 0.954613,-1.34274595 0.228515,-1.42187505 z M 11.992188,5.4648438 c 1.407906,0.011973 2.352596,0.2168424 2.552734,0.5625 0.0933,0.1611317 0.121143,0.4434628 0.0625,0.6445312 -0.0887,0.3041478 -0.369818,0.4211402 -0.78125,0.3242188 C 13.685852,6.9630408 13.289203,6.903046 12.943359,6.8632812 12.597515,6.823516 12.131329,6.7699428 11.908203,6.7421875 11.28857,6.6651076 9.7188276,6.7437391 8.5820312,6.9101562 7.4965784,7.069059 6.8273729,7.282237 6.046875,7.71875 5.5675559,7.9868206 5.4161794,8.0518712 5.234375,8.0625 4.9629176,8.0783734 4.9121094,8.0533013 4.9121094,7.9179688 c 0,-0.1908283 0.3435755,-0.4884335 0.9941406,-0.8613282 1.7588725,-1.0081644 3.5524557,-1.5297084 5.455078,-1.5839844 0.219157,-0.00624 0.429727,-0.0095 0.63086,-0.00781 z m 4.414062,0.8847656 c 0.588792,-0.022181 1.223508,0.5393547 0.492188,1.359375 C 16.41395,8.0478239 15.703125,7.6792496 15.703125,7.0898438 15.716875,6.5864357 16.052976,6.3629179 16.40625,6.3496094 Z M 5.8554688,9.78125 c 0.78619,0.00144 1.5698436,0.26308 2.1542968,0.8125 0.5861454,0.514395 0.9576166,1.273977 0.953125,2.058594 0.025527,1.902469 -2.0626284,3.232051 -3.8261718,2.810547 C 3.4962994,15.215462 2.1972072,13.422892 2.796875,11.802734 3.2255886,10.497718 4.5451524,9.7788526 5.8554688,9.78125 Z M 18,9.8984375 c 0.786189,0.00144 1.569844,0.2630785 2.154297,0.8125005 0.586146,0.514395 0.957616,1.275929 0.953125,2.060546 0.02553,1.902467 -2.062629,3.23205 -3.826172,2.810547 C 15.64083,15.334602 14.343691,13.54008 14.943359,11.919922 15.372071,10.614906 16.689683,9.8960402 18,9.8984375 Z M 5.7480469,11.345703 a 1.1736641,1.1736641 0 0 0 -1.1503907,1.173828 1.1736641,1.1736641 0 0 0 1.1738282,1.173828 1.1736641,1.1736641 0 0 0 1.171875,-1.173828 1.1736641,1.1736641 0 0 0 -1.171875,-1.173828 1.1736641,1.1736641 0 0 0 -0.023437,0 z m 12.4550781,0.210938 a 1.1736641,1.1736641 0 0 0 -1.152344,1.173828 1.1736641,1.1736641 0 0 0 1.173828,1.173828 1.1736641,1.1736641 0 0 0 1.173829,-1.173828 1.1736641,1.1736641 0 0 0 -1.173829,-1.173828 1.1736641,1.1736641 0 0 0 -0.02148,0 z m -7.298828,2.191406 c 0.648752,0.265903 1.697199,0.144527 2.082031,0.101562 -1.192729,1.229945 -2.082031,-0.101562 -2.082031,-0.101562 z m 8.921875,4.548828 c -0.958544,1.245584 -2.506036,1.942343 -3.986328,2.400391 -1.287521,0.355127 -2.625164,0.534662 -3.960938,0.521484 -2.7356683,-0.03572 -5.5378609,-0.90746 -7.597656,-2.751953 0.6457891,0.127717 1.9342179,0.912694 2.9042969,1.119141 2.2408497,0.69508 4.6288071,0.724352 6.9277341,0.324218 1.964769,-0.276517 3.925735,-0.73109 5.712891,-1.613281 z M 4.78125,21.09375 c 0.3552371,1.436081 2.4239608,0.180898 2.6894531,1.394531 -0.030766,0.48728 -0.5889311,0.564293 -0.9667969,0.501953 C 5.5234403,23.142395 4.3391396,21.474229 4.78125,21.09375 Z m 14.224609,0.503906 c 0.108254,0.0019 0.214704,0.02709 0.322266,0.08203 0.542884,0.908263 -0.67981,1.521172 -1.443359,1.3125 -0.451408,-0.03853 -1.540014,-0.788328 -1.306641,-1.025391 0.888494,0.698579 1.669957,-0.382354 2.427734,-0.369141 z'
```

**Comment by clemalex824** [comment]
Here is link to the presentation of the module in French with directive sharing svg path 👍

https://forum.hacf.fr/t/ajouter-creer-des-icones/4190?u=clemalex
