### ISSUE TITLE
SVG path question

### ISSUE THREAD

**Issue by NightFalcon650** [hulkhaugen/hass-bha-icons#19]
I want to add my own icons and succeeded more or less.
I added my own iconset and changed the name etc. 
I have some png wich i converted to a svg. I downloaded this SVG and opened it with a tekst editor. Copied the part after d= and put this in my js file. 
HA loads the JS, but the picture is shown as one black rectangle.. How is this possible?
It there something wrong with the path (aldo when i open the svg as a picture it shows right)?
Is there a good and easy converter fot converting PNG (or other pictures) to SVG,, directly working with HA?
And what settings?

Hoping someone could help me out with this.
Thanks in advance :-D

**Comment by hulkhaugen** [comment]
My guess would be that your image is to big for the viewbox. You can look at the numbers inside the `path d="x"`, all of those are coordinates and should be less than 24, as the viewbox for these icons are 24x24. Have you previewed the svg in a browser or opened it in an SVG editor software? If it is indeed the size, resizing is easy using Inkscape or similar.

Another possibility is that you've messed up the syntax in the js file, but i'm sure you've already checked that.

As for converting png to svg, that is not optimal in my opinion, but the better the resolution of the png, the better the result will be. I've used convertes myself sometimes, and have seen different results with different converters, it's a bit hit and miss.

**Comment by clemalex824** [comment]
Personally when I start from an image I use gimp to create the path of the svg

**Comment by NightFalcon650** [comment]
Thanks for the reactions.
I'd didn't messed up the js, because the other allready existing icons work normaly. Only the one where i changed the path is showing like described.

I'm not that femiliair with svg, gimp etc. 
For example i'm trying to make a iconset out of the png from this github link [https://github.com/jcrowegitHu8/home-assistant-icons](url)
Does anybody have a (noob) tutorial to convert png files to the correct size svg and getting the path out of it? 
(the last one is in my opinion opening the svg in a text editor)

**Comment by hulkhaugen** [comment]
Honestly, those icons are very easy to draw, and will give you a much better result than converting a png. I suggest you download Inkscape and watch a tutorial on YouTube. You basically need two draw a few boxes, disable borders and apply fill, resize them to x.0 in height and width(>2.0 is recommended by material guidelines). Use the menu items `Path -> Union` to join pieces together (don't use groups) and `Path -> Difference` to remove space inside boxes, such as the "glass" of the windows.

**Comment by NightFalcon650** [comment]
Thanks for the reaction and excuse for my late reaction. 
In the meanwhile i downloaded inkscape and now the challange is to get to quick results plus extracting the path out of the svg.
Open to suggestions, also for converting from other pictures, due to the fact that these symols are rather easy to draw, but others aren't

**Comment by clemalex824** [comment]
> Ouvert aux suggestions, également pour la conversion à partir d'autres images, car ces symboles sont assez faciles à dessiner, mais d'autres ne le sont pas

I use GIMP and its magic sélection and i convert sélection to path.

I importe path in inkscape and continue to work (Take back the points of the svg)

**Comment by hulkhaugen** [comment]
> Thanks for the reaction and excuse for my late reaction.
> In the meanwhile i downloaded inkscape and now the challange is to get to quick results plus extracting the path out of the svg.
> Open to suggestions, also for converting from other pictures, due to the fact that these symols are rather easy to draw, but others aren't

You just open the svg-file in a text editor such as Notepad or better yet, Notepad++. Near the bottom of that file, you will see a line like `<path id="something" d="m12 22-1.6434-7.1085-6.5823 3.1472 4.533-5.7169-6.5646-3.1839 7.2959-0.020362-1.6036-7.1176 4.5649 5.6915l4.5649-5.6915-1.6036 7.1176 7.2959 0.020362-6.5646 3.1839 4.533 5.7169-6.5823-3.1472z" />`. The `id=""` might not be there, and other stuff might be there. What you want is the content inside the `d=""`. If there are several paths, you should merge/union them. If the path(s) are inside (between) `<g optional="content">` and `</g>` tags, it means that they are grouped, you don't want that.

**Comment by NightFalcon650** [comment]
thanks for the reaction.
I've tryed it with inkscape, but didn't succeed.
I've saved it with inkscape and the code in notepad++ gives the following:

``````
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="32px"
   height="32px"
   viewBox="0 0 32 32"
   version="1.1"
   id="svg14"
   sodipodi:docname="00, bulbsSpot.svg"
   inkscape:version="1.0.2-2 (e86c870879, 2021-01-15)">
  <sodipodi:namedview
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1"
     objecttolerance="10"
     gridtolerance="10"
     guidetolerance="10"
     inkscape:pageopacity="0"
     inkscape:pageshadow="2"
     inkscape:window-width="1920"
     inkscape:window-height="1001"
     id="namedview9"
     showgrid="false"
     inkscape:zoom="12.96875"
     inkscape:cx="16.388377"
     inkscape:cy="11.800781"
     inkscape:window-x="-9"
     inkscape:window-y="-9"
     inkscape:window-maximized="1"
     inkscape:current-layer="svg14" />
  <metadata
     id="metadata18">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title>bulbsSpot</dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <!-- Generator: Sketch 51.3 (57544) - http://www.bohemiancoding.com/sketch -->
  <title
     id="title2">bulbsSpot</title>
  <desc
     id="desc4">Created with Sketch.</desc>
  <defs
     id="defs6" />

     fill="#101010"
     id="g10"
     style="fill-rule:evenodd;image-rendering:pixelated"
     transform="translate(0.26235563,-0.19755426)">
    <path
       id="path8"
       d="m 16,5 c -2.600654,0.042187 -5.292601,0.218634 -7.703125,1.2792969 -0.9687823,0.2646202 -1.8754363,1.5878252 -0.75,2.2851562 1.6189181,1.1233467 3.659814,1.3586385 5.566406,1.6015629 3.329264,0.279308 6.776395,0.206937 9.966797,-0.8750004 C 23.862695,8.9618496 25.027915,8.5307929 24.988281,7.515625 24.644223,6.4839488 23.435226,6.1563393 22.513672,5.8222656 20.406186,5.1953013 18.190281,5.0118966 16,5 Z m -7.7851562,5.085938 c 0.3798247,2.425119 1.512004,4.849528 3.5625002,6.294921 0.39552,0.609796 0.162177,1.398613 0.222656,2.091797 0.02939,1.081607 -0.06681,2.172624 0.06445,3.246094 0.336685,1.338632 1.893772,1.651678 3.080078,1.742188 1.448098,0.05303 3.102706,0.105592 4.289063,-0.863282 0.817101,-0.792349 0.503695,-1.984849 0.566406,-2.998047 0.02283,-0.981457 -0.05591,-1.971185 0.06445,-2.945312 0.490814,-0.668259 1.301054,-1.102235 1.771485,-1.824219 1.071692,-1.365074 1.663971,-3.046887 1.949218,-4.74414 -2.716697,1.057719 -5.688337,1.239663 -8.576172,1.208984 -2.36218,-0.09371 -4.781528,-0.323149 -6.9941402,-1.208984 z M 13,23.925781 c 0.03663,0.819392 -0.08347,1.659315 0.07813,2.462891 0.454257,1.153089 2.21248,0.471675 1.92187,-0.673828 v -1.257813 c -0.687175,-0.06849 -1.389574,-0.191138 -2,-0.53125 z m 6,0 c -0.511529,0.555403 -1.8733,0.152941 -2,0.816407 0.06521,0.707747 -0.229449,1.591909 0.441406,2.085937 0.87881,0.598449 1.76795,-0.401654 1.558594,-1.283203 z" /> 
</svg>
``````

I also tryed reverse-engineering like saving a svg and changed the pad with a iconpath wich works. When i open the changed svg it opens in inkscape.  

I think there is something wrong with the way how inkscape saves it. I can't figure out what's wrong.

**Comment by ur7x** [comment]
I have noticed this too... Inkscape is very hit an miss on creating an SVG "string" that BHA can understand.  Often Inkscape seems to have some hidden scaling to the SVG that results in a tiny icon in BHA/HASS..  Some times it works, most times nope...  Inkscape sometimes saves the icon with mm dimensions in spite of having set the document to px.

**Comment by hulkhaugen** [comment]
I see a couple of problems, on being the transform="translate(xxx) part. This is basically an offset that moves the item(s) from one position to another, but won't be included when you only copy the path `d=""`-part. The other one being:
```
width="32px"
height="32px"
viewBox="0 0 32 32"
```
The default for HA is 24x24. There is no reason why 32x32 shouldn't work, but the content needs to be adjusted for that. I think this is what you want (complete svg file content without the nonsense):

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
<svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="m11.992 0.99522c-2.6006 0.04219-5.2926 0.21863-7.7031 1.2793-0.96879 0.26462-1.8754 1.5878-0.75 2.2852 1.6189 1.1234 3.6598 1.3586 5.5664 1.6016 3.3293 0.2793 6.7764 0.20693 9.9668-0.875 0.78261-0.32917 1.9478-0.76023 1.9082-1.7754-0.34406-1.0317-1.553-1.3593-2.4746-1.6934-2.1075-0.62697-4.3234-0.81037-6.5137-0.82227zm-7.7852 5.0859c0.37983 2.4251 1.512 4.8495 3.5625 6.2949 0.39552 0.6098 0.16218 1.3986 0.22266 2.0918 0.02939 1.0816-0.06681 2.1726 0.06445 3.2461 0.33669 1.3386 1.8938 1.6517 3.0801 1.7422 1.4481 0.05303 3.1027 0.10559 4.2891-0.86328 0.8171-0.79235 0.5037-1.9848 0.56641-2.998 0.02283-0.98146-0.05591-1.9712 0.06445-2.9453 0.49081-0.66826 1.301-1.1022 1.7715-1.8242 1.0717-1.3651 1.664-3.0469 1.9492-4.7441-2.7167 1.0577-5.6883 1.2397-8.5762 1.209-2.3622-0.09371-4.7815-0.32315-6.9941-1.209zm4.7852 13.84c0.03663 0.81939-0.08347 1.6593 0.07813 2.4629 0.45426 1.1531 2.2125 0.47168 1.9219-0.67383v-1.2578c-0.68717-0.06849-1.3896-0.19114-2-0.53125zm6 0c-0.51153 0.5554-1.8733 0.15294-2 0.81641 0.06521 0.70775-0.22945 1.5919 0.44141 2.0859 0.87881 0.59844 1.768-0.40166 1.5586-1.2832v-1.6191z"/>
</svg>
```

**Comment by hulkhaugen** [comment]
@NightFalcon650 
Is this what you had in mind?
![image](https://user-images.githubusercontent.com/1409758/116007021-0e069f00-a60e-11eb-8b6b-22f7545a26fb.png)

**Comment by NightFalcon650** [comment]
> @NightFalcon650
> Is this what you had in mind?
> ![image](https://user-images.githubusercontent.com/1409758/116007021-0e069f00-a60e-11eb-8b6b-22f7545a26fb.png)

yeah :-D
Does it work in HA?
Stil trying to figure out how to get the correct path D-value..
This so i can make all my icons now or in the feature working in HA

**Comment by hulkhaugen** [comment]
That would work, and this is the d-part:
`"m11.992 0.99522c-2.6006 0.04219-5.2926 0.21863-7.7031 1.2793-0.96879 0.26462-1.8754 1.5878-0.75 2.2852 1.6189 1.1234 3.6598 1.3586 5.5664 1.6016 3.3293 0.2793 6.7764 0.20693 9.9668-0.875 0.78261-0.32917 1.9478-0.76023 1.9082-1.7754-0.34406-1.0317-1.553-1.3593-2.4746-1.6934-2.1075-0.62697-4.3234-0.81037-6.5137-0.82227zm-7.7852 5.0859c0.37983 2.4251 1.512 4.8495 3.5625 6.2949 0.39552 0.6098 0.16218 1.3986 0.22266 2.0918 0.02939 1.0816-0.06681 2.1726 0.06445 3.2461 0.33669 1.3386 1.8938 1.6517 3.0801 1.7422 1.4481 0.05303 3.1027 0.10559 4.2891-0.86328 0.8171-0.79235 0.5037-1.9848 0.56641-2.998 0.02283-0.98146-0.05591-1.9712 0.06445-2.9453 0.49081-0.66826 1.301-1.1022 1.7715-1.8242 1.0717-1.3651 1.664-3.0469 1.9492-4.7441-2.7167 1.0577-5.6883 1.2397-8.5762 1.209-2.3622-0.09371-4.7815-0.32315-6.9941-1.209zm4.7852 13.84c0.03663 0.81939-0.08347 1.6593 0.07813 2.4629 0.45426 1.1531 2.2125 0.47168 1.9219-0.67383v-1.2578c-0.68717-0.06849-1.3896-0.19114-2-0.53125zm6 0c-0.51153 0.5554-1.8733 0.15294-2 0.81641 0.06521 0.70775-0.22945 1.5919 0.44141 2.0859 0.87881 0.59844 1.768-0.40166 1.5586-1.2832v-1.6191z"`

**Comment by NightFalcon650** [comment]
> That would work, and this is the d-part:
> `"m11.992 0.99522c-2.6006 0.04219-5.2926 0.21863-7.7031 1.2793-0.96879 0.26462-1.8754 1.5878-0.75 2.2852 1.6189 1.1234 3.6598 1.3586 5.5664 1.6016 3.3293 0.2793 6.7764 0.20693 9.9668-0.875 0.78261-0.32917 1.9478-0.76023 1.9082-1.7754-0.34406-1.0317-1.553-1.3593-2.4746-1.6934-2.1075-0.62697-4.3234-0.81037-6.5137-0.82227zm-7.7852 5.0859c0.37983 2.4251 1.512 4.8495 3.5625 6.2949 0.39552 0.6098 0.16218 1.3986 0.22266 2.0918 0.02939 1.0816-0.06681 2.1726 0.06445 3.2461 0.33669 1.3386 1.8938 1.6517 3.0801 1.7422 1.4481 0.05303 3.1027 0.10559 4.2891-0.86328 0.8171-0.79235 0.5037-1.9848 0.56641-2.998 0.02283-0.98146-0.05591-1.9712 0.06445-2.9453 0.49081-0.66826 1.301-1.1022 1.7715-1.8242 1.0717-1.3651 1.664-3.0469 1.9492-4.7441-2.7167 1.0577-5.6883 1.2397-8.5762 1.209-2.3622-0.09371-4.7815-0.32315-6.9941-1.209zm4.7852 13.84c0.03663 0.81939-0.08347 1.6593 0.07813 2.4629 0.45426 1.1531 2.2125 0.47168 1.9219-0.67383v-1.2578c-0.68717-0.06849-1.3896-0.19114-2-0.53125zm6 0c-0.51153 0.5554-1.8733 0.15294-2 0.81641 0.06521 0.70775-0.22945 1.5919 0.44141 2.0859 0.87881 0.59844 1.768-0.40166 1.5586-1.2832v-1.6191z"`

Hello
I tried it and first it wasn't working. 
So i've tryed and tryed the hole week and couldn't wrap my head arround why it wasn't working.

I started to look at other things and seen that the js file wasn't loaded completely when i checked the investigator of chrome. After clearing al the site data it loaded and showed the picture. 

So even if you restart HA and even the complete server it wasn't updating the HA-instance in the browser. So in the end i have to reset all the data and logon to HA for it to work. I got the images to work.

Only a new problem rised, in my Home-Assistant Companion App (android) the new icons, aren't displayed :-S
