### ISSUE TITLE
Request: Upside down light bulb please...

### ISSUE THREAD

**Issue by danielbrunt57** [hulkhaugen/hass-bha-icons#21]
Can you add an upside down version of this?
mdi-lightbulb-on-outline &/or mdi-lightbulb-outline

**Comment by hulkhaugen** [comment]
Like this?
![image](https://user-images.githubusercontent.com/1409758/116305183-b863fb00-a7a3-11eb-83d8-177a121a881a.png)
![image](https://user-images.githubusercontent.com/1409758/116305407-0842c200-a7a4-11eb-83f4-fb7c1b8b71fe.png)
![image](https://user-images.githubusercontent.com/1409758/116305044-8357a880-a7a3-11eb-9909-9bbe00894398.png)

**Comment by danielbrunt57** [comment]
Perfect!

**Comment by hulkhaugen** [comment]
added
