### ISSUE TITLE
Icons are not displayed after update

### ISSUE THREAD

**Issue by SAOPP** [hulkhaugen/hass-bha-icons#22]
Hi!

Very strange, but today after updating to the version to this commit: https://github.com/hulkhaugen/hass-bha-icons/commit/e9feb799f7f47d18d960fe7c0e3664dff7a1bb6a

Newly added icons are not displayed, and sometimes after the page is updated, those that were in the package before the current update also disappear.

![image](https://user-images.githubusercontent.com/5647009/116038820-9cad0780-a672-11eb-81bb-4cd746ff2009.png)
```
            - type: light
              entity: light.yeelight_kitchen_ceiling
              icon: bha:ceiling-lamp-round
              name: Люстра
            - type: light
              entity: light.yeelight_kitchen_ceiling_nightlight
              icon: mdi:weather-night
              name: Ночник
            - type: light
              entity: light.kitchen_downlights_group
              icon: bha:ceiling-downlight
              name: Потолочные
```

**Comment by SAOPP** [comment]
..and this after refresh the page, all old icons are hide too:

![image](https://user-images.githubusercontent.com/5647009/116041691-2ad6bd00-a676-11eb-9021-235872ce97b2.png)

**Comment by hulkhaugen** [comment]
That is indeed strange as the only change done is adding 3x icons: c30e70446ed2da5b5ff596b449400c1edad2b273

I'm currently at a very restricted work computer and am unable to reproduce what you're seeing. On my dev setup, they all work fine, even the new ones.

- What browser are you using?
- Have you tried in incognito/private mode?

**Comment by SAOPP** [comment]
I agree, roughly speaking, there are no changes. Today I am had updated hacks and your component together.

Chrome 90.0.4430.85.

I have not tried to re-login, but now I will try to do it.

**Comment by SAOPP** [comment]
![image](https://user-images.githubusercontent.com/5647009/116048019-6923aa80-a67d-11eb-8ec6-9a669eeb4ed1.png)

Here is under incognito mode, on the right, there should be a smoke sensor icon.

Last chance I will try with ff...

**Comment by SAOPP** [comment]
Here is screen from my mobile chrome, and the same thing, and I cleared cache before opened:

![image](https://user-images.githubusercontent.com/5647009/116049265-c409d180-a67e-11eb-95f0-55dd8114b825.png)

Also I'm login to HA with FF, and I don't see this issue over here. Really very interesting, w...t...f... :(

**Comment by SAOPP** [comment]
I cleared the cookies in my Chrome, opened the HA, login into it, the first load of the page - everything is displayed fine, but as soon as I refresh the page, I again do not see the icons from the BHA.

**Comment by hulkhaugen** [comment]
What OS are you running, and what version of HA?

Can you try:
- Ctrl + Shift + R
- If that doesn't work, try right-click and select `Inspect`. Click on the `Network` tab, check the `Disable cache` check box and hit refresh with the `Inspect` panel open?

**Comment by SAOPP** [comment]
It looks like the situation has stabilized. Not sure 'bout my browser strange behaviour... I will monotored this.

'bout my stuff, it's Ubuntu. HA I'm using the latest at current moment `2021.4.6`.
