### ISSUE TITLE
https://github.com/hulkhaugen/hass-bha-icons is not a valid add-on repository

### ISSUE THREAD

**Issue by Quarco** [hulkhaugen/hass-bha-icons#23]
Can't add the repository, this message appears in the logs...
https://github.com/hulkhaugen/hass-bha-icons is not a valid add-on repository

Am I doing something wrong then? Should be the URL of the repository??

**Comment by hulkhaugen** [comment]
Yes, you are. This is not an add-on, it's an integration(custom component). You either install it using [HACS](https://hacs.xyz/), or you follow the manual installation guide here: https://github.com/hulkhaugen/hass-bha-icons

**Comment by Quarco** [comment]
That was it! Thanks @hulkhaugen 
In lovelace it works perfectly. Used the system-wide setting in config.yaml 

Want it to use it in [Tileboard](https://community.home-assistant.io/t/tileboard-new-dashboard-for-homeassistant/57173), but can't use it there. Something to sort out then.
