### ISSUE TITLE
Request: Night light icon

### ISSUE THREAD

**Issue by dagwud** [hulkhaugen/hass-bha-icons#24]
Could you please consider adding an icon for a night light (for kids)?

e.g. something to represent a product like this:
https://www.walmart.com/ip/Star-Projector-Lamp-Night-Light-360-Degree-Romantic-Room-Rotating-Cosmos-Projuctor-Christmas-Decorations-Starry-Moon-Sky-Kid-Bedroom/947151617

**Comment by dagwud** [comment]
Here're some mockups I created myself for this purpose; feel free to use/adjust as necessary
[night-light.tar.gz](https://github.com/hulkhaugen/hass-bha-icons/files/6547623/night-light.tar.gz)

**Comment by hulkhaugen** [comment]
That icon is not suited due to the amount of details for these icons. That's not saying we can't come up with a simpler alternative. Here's a link to the guidelines I'm trying to follow: https://material.io/design/iconography/system-icons.html#grid-and-keyline-shapes

**Comment by dagwud** [comment]
Fair enough; how about something like this?

[untitled.zip](https://github.com/hulkhaugen/hass-bha-icons/files/6589076/untitled.zip)

**Comment by hulkhaugen** [comment]
Sorry, forgot about this, added now ;)
